FROM  ghcr.io/maxirmx/gentoo-toolbox-container:latest

RUN cd root && \
    git clone https://github.com/facebook/proxygen.git --depth 1 && \
    cd proxygen/proxygen  && \
    sed s/\-DCMAKE_INSTALL_PREFIX=\"\$DEPS_DIR\"/\-DCMAKE_INSTALL_PREFIX=\"\$PREFIX\"/ < build.sh > b.sh && \
    chmod +x b.sh && \ 
    ./b.sh  --no-tests --prefix /usr/local && \
    ./install.sh && \
    rm -rf _build 
